server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  tomcat:
    accept-count: 500
    max-connections: 10000
    threads:
      max: 500
      min-spare: 500

spring:
  application:
    name: springbootsample
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver